### ISSUE TITLE
RPC call doesn't use timeout when an erlang node is down [v1.2.2]

### ISSUE THREAD

**Issue by Noksa** [ergo-services/ergo#50]
Hello!

I've found a new defect after 1.2.2.

You can easily reproduce it. Just call `CallRPCWithTimeout` function when an erlang node is down.

Log:
```
2021/05/11 09:52:16 [test@MBP-Alexandr] RPC calling: demo@MBP-Alexandr:erlang:system_info
2021/05/11 09:52:16 [test@MBP-Alexandr] sending message by tuple [rex demo@MBP-Alexandr]
2021/05/11 09:52:16 [test@MBP-Alexandr] can't connect to demo@MBP-Alexandr: Can't resolve port for demo@MBP-Alexandr: desired node not found
```
And the app is stuck

**Comment by halturin** [comment]
It seems the recent change caused this issue (Golang doc says we should read the channel if Stop() returns 'false', but it freezes in a certain case). Golang got a new timer behavior in the latest releases. It a bit confused me. Im going to fix it right away.

**Comment by halturin** [comment]
fixed and republished v1.2.2

**Comment by Noksa** [comment]
Oh thanks, you are so fast :)

**Comment by halturin** [comment]
just warming up before the work 😄

**Comment by Noksa** [comment]
I tried to remove the entire ~/go/pkg/mod directory and used `go clean -modcache`.
But I can't download the last version which was republished.
I even tried `go get github.com/halturin/ergo@92cfd8f212cfef9ef2a9eb68dabbb7132bdb6f3a` but still have the old version.

Do you know how I can download republished version?

**Comment by halturin** [comment]
Its wierd. v1.2.2 points to 92cfd8f commit which is the latest one https://github.com/halturin/ergo/releases/tag/v1.2.2

ps: might be it wasn't a good idea to update the release tag.

**Comment by Noksa** [comment]
Yeah, I can't figure out why golang still downloads previous version even if I use the latest commit's hash

**Comment by halturin** [comment]
I think i know. Along with go.mod there is go.sum which is points to the outdated commit. remove this file. it should be autogenerated.

**Comment by Noksa** [comment]
I found some info about republishing: https://golang.org/doc/modules/publishing
```
Note: Don't change a tagged version of a module after publishing it. For developers using the module, Go tools authenticate a downloaded module against the first downloaded copy. If the two differ, Go tools will return a security error. Instead of changing the code for a previously published version, publish a new version.
```

**Comment by halturin** [comment]
Just created a new tag - v1.2.2.1. Hope it fixes this problem.

**Comment by halturin** [comment]
what a beautiful day :). created another one - v1.2.3.

**Comment by Noksa** [comment]
Haha, sorry for that :)
And thanks a lot for your patience and help. Now it works! 
I hope it was the last issue from me.
